import { jsPDF } from "jspdf";

export default function exportLogPDF(log) {
  const doc = new jsPDF();

  let y = 20;

  doc.setFontSize(20);
  doc.text("AI IT Support Report", 20, y);

  y += 15;

  doc.setFontSize(12);
  doc.text(`Filename: ${log.filename}`, 20, y);

  y += 10;
  doc.text(`Severity: ${log.severity}`, 20, y);

  y += 10;
  doc.text(`Category: ${log.category}`, 20, y);

  y += 10;
  doc.text(
    `Generated: ${new Date(log.createdAt).toLocaleString()}`,
    20,
    y
  );

  y += 20;

  doc.setFontSize(16);
  doc.text("Original Log", 20, y);

  y += 10;

  doc.setFontSize(11);

  const original = doc.splitTextToSize(
    log.originalText || "No log available",
    170
  );

  doc.text(original, 20, y);

  y += original.length * 7 + 10;

  doc.setFontSize(16);
  doc.text("AI Analysis", 20, y);

  y += 10;

  doc.setFontSize(11);

  const analysis = doc.splitTextToSize(
    log.analysis || "No analysis available",
    170
  );

  doc.text(analysis, 20, y);

  y += analysis.length * 7 + 20;

  doc.setFontSize(10);
  doc.text(
    "Generated by AI IT Support Assistant",
    20,
    y
  );

  doc.save(`${log.filename}.pdf`);
}